name: mlag_cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - numpy=1.23.5
  - absl-py=2.3.1
  - attrs=25.4.0
  - cattrs=1.5.0
  - certifi=2025.10.5
  - charset-normalizer=3.3.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - exceptiongroup=1.3.0
  - filelock=3.17.0
  - fsspec=2025.9.0
  - grpcio=1.48.2
  - gym=0.26.2
  - gym-notices=0.1.0
  - h5py=3.14.0
  - huggingface-hub=0.35.3
  - idna=3.7
  - jinja2=3.1.6
  - markdown=3.9
  - markupsafe=3.0.2
  - mlagents=1.1.0
  - mlagents-envs=1.1.0
  - mpmath=1.3.0
  - networkx=3.4.2
  - onnx=1.15.0
  - packaging=25.0
  - pettingzoo=1.15.0
  - pillow=11.1.0
  - protobuf=3.20.3
  - pypiwin32=223
  - pywin32=311
  - pyyaml=6.0.2
  - requests=2.32.5
  - six=1.17.0
  - sympy=1.13.1
  - tensorboard=2.20.0
  - tensorboard-data-server=0.7.2
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - urllib3=2.5.0
  - werkzeug=3.1.3
  - pip
  - pip:
      - torch==2.5.1+cpu
      - torchvision==0.20.1+cpu
      - torchaudio==2.5.1+cpu
